CREATE TABLE IF NOT EXISTS pessoa(
    id INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
    name CHAR(60) NOT NULL,
    age INT(3) NOT NULL,
    PRIMARY KEY(id) 
);

CREATE TABLE IF NOT EXISTS transacao(
    id INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
    descricao CHAR(60) NOT NULL,
    value FLOAT NOT NULL,
    id_pessoa INT(5) UNSIGNED ZEROFILL NOT NULL,
    id_type INT(5) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS tipo(
    id INT(1) NOT NULL AUTO_INCREMENT,
    descricao CHAR(10) NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE transacao ADD FOREIGN KEY (id_type)REFERENCES tipo(id);
ALTER TABLE transacao ADD FOREIGN KEY (id_pessoa)REFERENCES pessoa(id) ON DELETE CASCADE;
INSERT INTO tipo VALUES(null, "Receita");
INSERT INTO tipo VALUES(null, "Despesa");
